name: PHP

on:
    workflow_call:

jobs:
    call-analyse-workflow:
        name: Analyse code for SwagPaymentPayPalUnified
        uses: shopware5/docker-images-testing/.github/workflows/php-code-analysis.yml@main
        with:
            plugin-name: SwagPaymentPayPalUnified
